# Generated by Django 3.0.1 on 2022-06-10 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_auto_20220610_0812'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
