# Generated by Django 3.0.1 on 2022-06-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20220615_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='recepient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='user_app.Profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.Profile'),
        ),
    ]
