# Generated by Django 3.0.1 on 2022-06-15 17:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_auto_20220615_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 17, 50, 29, 267812, tzinfo=utc)),
        ),
    ]
