# Generated by Django 3.0.1 on 2022-06-20 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_chat_modified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-modified']},
        ),
    ]
