# Generated by Django 3.0.1 on 2022-06-15 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20220615_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='recepient',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.Message'),
        ),
    ]
