# Generated by Django 3.0.1 on 2022-06-15 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_auto_20220615_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['messages']},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='id',
            new_name='unique_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 15, 16, 25, 8, 106175)),
        ),
    ]
