# Generated by Django 3.0.1 on 2022-06-20 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_auto_20220615_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
